version: '3.3'
services:

  home.postgres:
    image: postgres:latest
    container_name: home.postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - 7000:5432
    volumes:
      - "$HOME/docker/home/postgres:/var/lib/postgresql/data"
      - "$HOME/docker/home/log:/var/log/postgres"
      - "./examples/config/postgres/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql"
      - "./examples/config/postgres/postgresql.conf:/postgresql.conf"
    networks:
      default:
        aliases:
          - home.postgres

  home.rabbitmq:
    image: rabbitmq:3.7.7-management
    container_name: home.rabbitmq
    hostname: rabbitmq
    environment:
      RABBITMQ_DEFAULT_VHOST: local
      RABBITMQ_DEFAULT_USER:  root
      RABBITMQ_DEFAULT_PASS:  password
    volumes:
      - "$HOME/docker/rabbitmq:/var/lib/rabbitmq:rw"
    ports:
      - 15673:15672
      - 5673:5672
    networks:
      default:
        aliases:
          - home.rabbitmq

volumes:
  esdata1:
    driver: local
